import { parseJudgeOutput } from "./judge";

// LLM-judge invocation + final score decision, shared by the in-container
// harness (unsealed / non-SWE runs) and scripts/finalize-sealed-result.ts
// (sealed runs: the judge runs on the HOST, after grading in a fresh
// container, so the agent container never holds expectedDiff or a judge key).

export type ScoreSource = "container-test" | "fresh-container-test" | "judge" | "judge-parse-failed" | "harness-error";

// Picks the judge model: --judge-model when given and resolvable, else the
// agent model. Warns on self-grading, comparing provider AND id (same id on
// a different provider, e.g. local ds4 vs openrouter, is not self-grading).
export function resolveJudgeModel(modelRegistry: any, judgeModelReq: any, defaultJudgeModel: any): any {
  let judgeModel = defaultJudgeModel;
  if (judgeModelReq) {
    const resolved = modelRegistry.find(judgeModelReq.provider, judgeModelReq.id);
    if (resolved) {
      judgeModel = resolved;
    } else {
      console.warn(`[WARN] Could not resolve judge model ${judgeModelReq.provider}/${judgeModelReq.id}. Using default.`);
    }
  }
  if (!judgeModel) throw new Error("Judge model not found");
  if (
    defaultJudgeModel &&
    judgeModel.provider === defaultJudgeModel.provider &&
    judgeModel.id === defaultJudgeModel.id
  ) {
    console.warn(`\n[WARN] Judge model is the SAME as the agent model (${judgeModel.provider}/${judgeModel.id}) — the model is grading its own output.
For SWE-bench tasks the container test now decides the score, so this only affects the rationale.
Pass --judge-model (e.g. openrouter/deepseek/deepseek-v4-pro) for an independent judge.\n`);
  }
  console.log(`[INFO] Judge model: ${judgeModel.provider}/${judgeModel.id}`);
  return judgeModel;
}

export interface JudgePromptInput {
  task: any;
  expectedDiff: string;
  diff: string;
  testExitCode: number | null;
  testOutput: string;
  isSweContainer: boolean;
}

export const JUDGE_SYSTEM_PROMPT = `You are an expert software engineer reviewing the output of an AI coding agent.
You will be provided with the task prompt, the expected behavior, the git diff generated by the agent, and optionally a known correct "solution diff" and automated test output.
Your job is to determine if the diff successfully accomplishes the task and explain why (or why not).
- If automated tests were run and PASSED, the patch is accepted: score 1 with a concise explanation.
- If automated tests were run and FAILED, the patch did NOT satisfy the acceptance tests: score 0 unless you have a compelling reason the failure is unrelated to the change (e.g. a pre-existing/environment failure), which you must explain in the rationale.
- If no automated tests were run, judge the diff on its own merits against the expected behavior and the known correct solution.
Respond ONLY with a JSON object in this exact format, with no markdown wrapping:
{
  "score": 0 or 1,
  "rationale": "Explanation for the score"
}`;

export function buildJudgePrompt({ task, expectedDiff, diff, testExitCode, testOutput, isSweContainer }: JudgePromptInput): string {
  let truncatedTestOutput = testOutput;
  if (truncatedTestOutput.length > 15000) {
    truncatedTestOutput = truncatedTestOutput.substring(0, 5000) + "\n\n...[TRUNCATED]...\n\n" + truncatedTestOutput.substring(truncatedTestOutput.length - 10000);
  }

  let testResultsSection = "";
  if (testExitCode !== null) {
    const testSource = isSweContainer ? "SWE-bench Container" : "Local";
    testResultsSection = `Automated Test Execution (${testSource}):\nExit Code: ${testExitCode}\nTests: ${isSweContainer && task.failToPass ? task.failToPass.join(", ") : (task.testCommand || "N/A")}\nOutput:\n${truncatedTestOutput}\n`;
  }

  return `Task Prompt:
${task.prompt}

Expected Behavior:
${task.expectedBehavior || "Not specified."}

${expectedDiff ? `Known Correct Solution Diff:\n${expectedDiff}\n` : ""}
Agent Diff:
${diff ? diff : "(No changes made)"}

${testResultsSection}
`;
}

export interface JudgeOutcome {
  judgeScore: number | null;
  rationale: string;
  judgeParseFailed: boolean;
  judgeAttemptsUsed: number;
}

export async function runJudge(modelRuntime: any, modelRegistry: any, judgeModel: any, judgePrompt: string): Promise<JudgeOutcome> {
  const auth = await modelRegistry.getApiKeyAndHeaders(judgeModel);
  if (!auth.ok) throw new Error("Judge auth failed: " + auth.error);

  let judgeScore: number | null = null;
  let rationale = "Failed to parse judge output";
  let judgeParseFailed = true;
  let judgeAttemptsUsed = 0;
  const maxJudgeAttempts = 3;
  for (let attempt = 1; attempt <= maxJudgeAttempts; attempt++) {
    judgeAttemptsUsed = attempt;
    let judgeOutput = "";
    const stream = modelRuntime.streamSimple(judgeModel, {
      systemPrompt: JUDGE_SYSTEM_PROMPT,
      messages: [{ role: "user", content: judgePrompt, timestamp: Date.now() }]
    }, { apiKey: auth.apiKey, headers: auth.headers });

    for await (const chunk of stream) {
      if (chunk.type === "text_delta") {
        judgeOutput += chunk.delta;
      }
      if (chunk.type === "error") {
        console.error("[DEBUG] streamSimple error:", chunk.error);
      }
    }
    const preview = judgeOutput.length > 500 ? judgeOutput.slice(0, 500) + "... [TRUNCATED]" : judgeOutput;
    console.log(`[DEBUG] Raw judge output (attempt ${attempt}/${maxJudgeAttempts}):`, preview);

    const parsed = parseJudgeOutput(judgeOutput);
    if (!parsed.parseFailed) {
      judgeScore = parsed.score;
      rationale = parsed.rationale;
      judgeParseFailed = false;
      break;
    }
    console.error(`[ERROR] Failed to parse judge output (attempt ${attempt}/${maxJudgeAttempts}): ${parsed.rationale.slice(0, 300)}`);
    rationale = parsed.rationale;
    if (attempt < maxJudgeAttempts) {
      console.log(`[INFO] Retrying LLM judge...`);
    }
  }
  return { judgeScore, rationale, judgeParseFailed, judgeAttemptsUsed };
}

export interface ScoreInput {
  // True when the score comes from SWE FAIL_TO_PASS tests (in-container or fresh).
  isSweTestTask: boolean;
  harnessError: boolean;
  testExitCode: number | null;
  judgeScore: number | null;
  judgeParseFailed: boolean;
  // Which ground-truth source a test result counts as.
  testSource?: "container-test" | "fresh-container-test";
}

// Ground-truth-first scoring: for SWE-bench tasks the FAIL_TO_PASS test
// result DECIDES the score; the LLM judge only explains (its raw verdict is
// recorded separately). For other tasks the judge decides; unparseable judge
// output defaults to 0. A harness error (malformed FAIL_TO_PASS -- see
// task-validation.ts) is checked FIRST: it also has testExitCode === null,
// but must never fall through to the judge, which never saw a real test.
export function decideScore(input: ScoreInput): { scoreSource: ScoreSource; finalScore: number } {
  if (input.isSweTestTask && input.harnessError) {
    return { scoreSource: "harness-error", finalScore: 0 };
  }
  if (input.isSweTestTask && input.testExitCode !== null) {
    return { scoreSource: input.testSource ?? "container-test", finalScore: input.testExitCode === 0 ? 1 : 0 };
  }
  if (input.judgeScore !== null && !input.judgeParseFailed) {
    return { scoreSource: "judge", finalScore: input.judgeScore === 1 ? 1 : 0 };
  }
  return { scoreSource: "judge-parse-failed", finalScore: 0 };
}
